import Head from "next/head";

import { Image } from 'antd/lib';
import Title from "antd/lib/typography/Title";

import TypeErrorMessage from "./components/TypeErrorMessage/TypeErrorMessage";
import LoadingBlock from "./components/LoadingBlock/LoadingBlock";
import DownloadBtn from "./components/DownloadBtn/DownloadBtn";
import { UploadBlock } from "./components/UploadBlock/UploadBlock";
import CompareIdBtn from "./components/CompareIdBtn/CompareIdBtn";
import CompareMapBtn from "./components/CompareMapBtn/CompareMapBtn";
import MapSettings from "./components/MapSettings/MapSettings";
import RemoveDuplicateIdsBtn from "./components/RemoveDuplicateIdsBtn/RemoveDuplicateIdsBtn";
import RedefineIdsBtn from "./components/RedefineIdsBtn/RedefineIdsBtn";
import RenameBtn from "./components/RenameBtn/RenameBtn";
import RedefineAllIdsBtn from "./components/RedefineAllIdsBtn/RedefineAllIdsBtn";

export default function Home() {

  return (
    <>
      <Head>
        <title>IDs correction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"main-container"}>

        <Image className={"mainImg"} preview={false} src="img/svg/ak.svg"></Image>

        <Title className={"h1"}>
          <span className={"titleBlock"}>
            <span>Корректировка ID</span>
          </span>
        </Title>

        <main className={"main-block"}>

          <UploadBlock />

          <div className="btnWrapper">

            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>

              <CompareIdBtn />

              <RenameBtn />

              <RedefineAllIdsBtn />

            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>

              <CompareMapBtn />

              <RemoveDuplicateIdsBtn />

              <RedefineIdsBtn />

            </div>

          </div>

          <DownloadBtn />

          <TypeErrorMessage />

          <LoadingBlock />

          <MapSettings />

        </main>
      </div>
    </>
  );
}
